CREATE DEFINER=`root`@`localhost` EVENT `fill_att_sums` ON SCHEDULE EVERY 1 DAY STARTS '2021-07-16 23:30:50' ON COMPLETION NOT PRESERVE ENABLE DO CALL fill_att_sums()

CREATE DEFINER=`root`@`localhost` EVENT `fill_dut_sums` ON SCHEDULE EVERY 1 DAY STARTS '2021-07-16 02:08:50' ON COMPLETION PRESERVE ENABLE DO CALL fill_duty_sums()

CREATE DEFINER=`root`@`localhost` EVENT `fill_staffing_rate` ON SCHEDULE EVERY 1 MONTH STARTS '2021-07-16 04:09:47' ON COMPLETION PRESERVE ENABLE DO CALL staffing_rate()